package chat;


/**
* chat/ChatServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* mercredi 24 mai 2017 15 h 42 CEST
*/

public interface ChatServerOperations 
{
  void register (chat.ChatClient client);
  void unregister (chat.ChatClient client);
  void sendToAll (String msg, chat.ChatClient from);
} // interface ChatServerOperations
